spring:
  application:
    name: academic-recommendation-engine

  datasource:
    url: jdbc:postgresql://localhost:5432/edtech_db
    username: postgres
    password: ShuMika
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: 8080